version: '2'
services:

  mongo:
    image: sammlerio/mongo
    ports:
      - 27018:27017

  nats-streaming:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "4223:4223"
      - "8223:8223"
      - "8222:8222"
    volumes:
      - ./.datastore:/datastore
    command: [
      "-m", "8222",
      "--store", "FILE",
      "--dir", "datastore"
    ]

  audit-log-service:
    image: sammlerio/audit-log-service
    environment:
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=sammler_audit-log-service
      - NATS_STREAMING_HOST=nats-streaming
      - NATS_STREAMING_PORT=4222
    ports:
      - "3004:3004"
