swagger: '2.0'

info:
  version: "0.0.1"
  title: sammler-log-service
  license:
    name: MIT
host: localhost
schemes:
  - http
  - https
basePath: /v1
consumes:
  - application/json
produces:
  - application/json

################################################################################
#                                   Paths                                      #
################################################################################
paths:
  /logs:
    post:
      description: Post `log` object.
      parameters:
        - name: log
          in: body
          schema:
            $ref: '#/definitions/log'
      responses:
        201:
          description: Successfully created.
          schema:
            $ref: '#/definitions/logResult'
      tags:
        - Jobs
    get:
      description: Get all `log` objects.
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/logResult'
      tags:
        - Jobs


################################################################################
#                               Definitions                                    #
################################################################################
definitions:
  log:
    type: object
    properties:
      name:
        type: string

  logResult:
    type: object
    properties:
      _id:
        type: string
      name:
        type: string
      s5r_created_at:
        type: string
        format: date
      s5r_update_at:
        type: string
        format: date


